# Common properties for all applications go in this file
branding:
  restaurantName: Pivotal Bakery
  menuTitle: Pivotal Bakery Menu

menuBootstrap:
  items:
    - name: Scones
      price: 2
    - name: CupCakes
      price: 1
    - name: Eclairs
      price: 1.50
    - name: Caramels
      price: 0.50

targets:
  scheme: https
